/* GENETATED SOURCE CODE, DO NOT EDIT! */

/*
 * Copyright (c) 2014-2016, Intel Corporation
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


#include <iostream>

#include "dex/dex_to_dex_compiler.h"

// This was automatically generated by /Volumes/SSD/Android/inde-windows/art/tools/generate-operator-out.py --- do not edit!
namespace art {
namespace optimizer {
std::ostream& operator<<(std::ostream& os, const DexToDexCompilationLevel& rhs) {
  switch (rhs) {
    case DexToDexCompilationLevel::kDontDexToDexCompile: os << "DontDexToDexCompile"; break;
    case DexToDexCompilationLevel::kRequired: os << "Required"; break;
    case DexToDexCompilationLevel::kOptimize: os << "Optimize"; break;
  }
  return os;
}
}  // namespace optimizer
}  // namespace art

